language: php
dist: xenial

# Since Xenial services are not started by default, we need to instruct it below to start.
services:
  - xvfb
  - mysql

sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

# Test main supported versions of PHP against latest WP.
php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3

env:
  - WP_VERSION=latest WP_MULTISITE=0

# Additional tests against stable PHP (min version is 5.6)
# and code coverage report.
matrix:
  fast_finish: true
  include:
  - name: "Coding standard check"
    php: 7.2
    env: WP_VERSION=latest WP_MULTISITE=0 RUN_PHPCS=1
  - name: "e2e tests"
    php: 7.2
    env: WP_VERSION=latest WP_MULTISITE=0 RUN_E2E=1
    addons:
      chrome: beta
      apt:
        packages:
          - nginx
  - name: "Unit tests code coverage"
    php: 7.3
    env: WP_VERSION=latest WP_MULTISITE=0 RUN_CODE_COVERAGE=1
  - name: "WooCommerce unit tests using WordPress nightly"
    php: 7.3
    env: WP_VERSION=nightly WP_MULTISITE=0
  - php: 7.4snapshot
    env: WP_VERSION=nightly WP_MULTISITE=0
  allow_failures:
  - php: 7.3
    env: WP_VERSION=latest WP_MULTISITE=0 RUN_CODE_COVERAGE=1

# Specifies that Travis should create builds for master and release branches and also tags.
branches:
  only:
    - master
    - /^\d+\.\d+(\.\d+)?(-\S*)?$/
    - /^release\//